INSERT INTO COURSE (ID, NAME, DESCRIPTION)VALUES (1, 'JAVA', 'FORMACAO JAVA'); 
INSERT INTO COURSE (ID, NAME, DESCRIPTION)VALUES (2, 'WEB SERVICE SOAP', 'DESENVOLVENDO WEB SERVICE'); 
INSERT INTO COURSE (ID, NAME, DESCRIPTION)VALUES (3, 'CAMEL', 'INTEGRACAO ENTRE SISTEMAS'); 